'use client';

import { useMemo } from 'react';

function familyVolumeLabel(volume?: number, unit?: string): string {
  if (volume == null || !Number.isFinite(Number(volume))) return '';
  const u = String(unit || '').trim();
  return u ? `${volume} ${u}` : String(volume);
}

function displaySkuCell(item: { sku?: string }): string {
  const s = String(item.sku || '').trim();
  return s || '—';
}

interface InvoiceItem {
  qty: number;
  code: string;
  description: string;
  price: number;
  amount: number;
  sku?: string;
  familyId?: string;
  familyName?: string;
  familyCode?: string;
  familySku?: string;
  familyShortName?: string;
  familyVolume?: number;
  familyUnit?: string;
  /** Agrupación alineada al resumen por presentación (evita colapsar todo en una fila). */
  familyInvoiceKey?: string;
  /** Texto columna Presentation (nombre presentación + volumen). */
  presentationLabel?: string;
  /** Código genérico de la presentación (columna Code en vista familia). */
  presentationGenericCode?: string;
}

/** Clave estable por familia (id numérico normalizado, etc.), alineada con resúmenes. */
function familyGroupKey(item: InvoiceItem): string {
  const fid = String(item.familyId || '').trim();
  if (fid) {
    const n = Number(fid);
    if (!Number.isNaN(n)) return `i:${n}`;
    return `i:${fid.toLowerCase()}`;
  }
  const fs = String(item.familySku || '').trim().toLowerCase();
  if (fs) return `s:${fs}`;
  const fc = String(item.familyCode || '').trim().toLowerCase();
  if (fc) return `c:${fc}`;
  const fn = String(item.familyName || '').trim().toLowerCase();
  return `n:${fn || '_'}`;
}

/** Agrupación vista familia: prioriza `familyInvoiceKey` (presentación). Si falta, no colapsar toda la familia. */
function familyInvoiceGroupKey(item: InvoiceItem): string {
  const pres = String(item.familyInvoiceKey || '').trim();
  if (pres) return pres;
  return [
    familyGroupKey(item),
    String(item.presentationGenericCode || '').trim().toLowerCase(),
    String(item.presentationLabel || '').trim().toLowerCase(),
    String(item.sku || '').trim().toLowerCase(),
    String(item.code || '').trim().toLowerCase(),
  ].join('\u0001');
}

interface InvoiceProps {
  invoiceNumber: string;
  date: string;
  /** Código de ruta / vendedor (sin nombre). */
  vendorCode: string;
  storeName: string;
  storeAddress: string;
  items: InvoiceItem[];
  comments?: string;
  viewMode?: 'product' | 'family';
  printLayout?: 'normal' | 'ticket';
}

const L = {
  invoice: 'Invoice',
  date: 'Date',
  clientStore: 'Client / Store',
  vendor: 'Vendor',
  qty: 'Qty',
  code: 'Code',
  sku: 'SKU',
  description: 'Description',
  presentation: 'Presentation',
  unitPrice: 'Unit price',
  amount: 'Amount',
  totalUnits: 'Total units',
  total: 'Total',
  observations: 'Observations',
  footer: 'Generated by Eternal Cosmetics PWA · Eternal Cosmetics, LLC',
  noFamily: 'No family',
  noItems: 'No items',
  itemOrFamily: 'Item',
  familyLine: 'Family',
} as const;

export function Invoice({
  invoiceNumber,
  date,
  vendorCode,
  storeName,
  storeAddress,
  items,
  comments,
  viewMode = 'product',
  printLayout = 'normal',
}: InvoiceProps) {
  const productRows = useMemo(() => {
    const byKey = new Map<
      string,
      InvoiceItem & { qty: number; amount: number }
    >();
    items.forEach((it) => {
      const skuKey = displaySkuCell(it);
      const desc = String(it.description || '').trim();
      const price = Number(it.price) || 0;
      const key = `${skuKey}||${desc}||${price}`;
      if (!byKey.has(key)) {
        byKey.set(key, { ...it, qty: 0, amount: 0 });
      }
      const row = byKey.get(key)!;
      row.qty += Number(it.qty) || 0;
      row.amount += Number(it.amount) || 0;
      if (!String(row.sku || '').trim() && String(it.sku || '').trim()) row.sku = it.sku;
    });
    return [...byKey.values()].filter((x) => x.qty !== 0 || x.amount !== 0);
  }, [items]);

  const totalPcs = items.reduce((sum, item) => sum + item.qty, 0);
  const totalAmount = items.reduce((sum, item) => sum + item.amount, 0);

  const familyRows = useMemo(() => {
    const byFamily = new Map<
      string,
      {
        familyId: string;
        code: string;
        presentationDesc: string;
        qty: number;
        amount: number;
      }
    >();
    items.forEach((item) => {
      const familyId = String(item.familyId || '').trim();
      const familyName = (item.familyName || '').trim() || L.noFamily;
      const familySku = String(item.familySku || '').trim();
      const familyCode = String(item.familyCode || '').trim();
      const presGen = String(item.presentationGenericCode || '').trim();
      const key = familyInvoiceGroupKey(item);
      const vol = familyVolumeLabel(item.familyVolume, item.familyUnit);
      const short = String(item.familyShortName || '').trim();
      const presLine =
        String(item.presentationLabel || '').trim() ||
        [short, vol].filter(Boolean).join(' · ') ||
        familyName;
      if (!byFamily.has(key)) {
        byFamily.set(key, {
          familyId,
          code: presGen || familyCode || '—',
          presentationDesc: presLine,
          qty: 0,
          amount: 0,
        });
      }
      const row = byFamily.get(key)!;
      if ((!row.code || row.code === '—') && presGen) row.code = presGen;
      else if ((!row.code || row.code === '—') && familyCode) row.code = familyCode;
      if (!row.presentationDesc || row.presentationDesc === L.noFamily) {
        row.presentationDesc = presLine;
      }
      row.qty += Number(item.qty) || 0;
      row.amount += Number(item.amount) || 0;
    });
    return [...byFamily.values()]
      .map((r) => ({
        ...r,
        price: r.qty > 0 ? r.amount / r.qty : 0,
      }))
      .sort((a, b) => b.qty - a.qty || b.amount - a.amount);
  }, [items]);

  const vendorDisplay = String(vendorCode || '').trim() || '—';

  if (printLayout === 'ticket') {
    const rows =
      viewMode === 'family'
        ? familyRows.map((r) => ({
            left: `${r.code || '—'} ${r.presentationDesc || ''}`.trim(),
            qty: r.qty,
            price: r.price,
            amount: r.amount,
          }))
        : productRows.map((it) => ({
            left: `${displaySkuCell(it)} ${it.description || ''}`.trim(),
            qty: Number(it.qty) || 0,
            price: Number(it.price) || 0,
            amount: Number(it.amount) || 0,
          }));

    const ticketUnits = rows.reduce((s, r) => s + (Number(r.qty) || 0), 0);
    const ticketTotal = rows.reduce((s, r) => s + (Number(r.amount) || 0), 0);
    const ticketStore = String(storeName || '').trim() || '—';

    return (
      <>
        <style>{`
          @media print {
            #invoice-print.ticket-print {
              width: 58mm !important;
              max-width: 58mm !important;
              margin: 0 auto !important;
              box-shadow: none !important;
              border: 0 !important;
            }
          }
        `}</style>
        <div id="invoice-print" className="ticket-print bg-white text-black" style={{ fontFamily: 'monospace', fontSize: 11, padding: 6 }}>
          <div style={{ textAlign: 'center', marginBottom: 6 }}>
            <div style={{ fontWeight: 700 }}>ETERNAL COSMETICS</div>
            <div>{invoiceNumber || '—'}</div>
            <div>{date}</div>
          </div>
          <div style={{ marginBottom: 4 }}>
            <div>
              <strong>STORE:</strong> {ticketStore}
            </div>
            <div>
              <strong>VENDOR:</strong> {vendorDisplay}
            </div>
          </div>
          <div style={{ borderTop: '1px dashed #000', margin: '4px 0' }} />
          <div style={{ display: 'flex', justifyContent: 'space-between', fontWeight: 700 }}>
            <span>{viewMode === 'family' ? L.familyLine : L.itemOrFamily}</span>
            <span>QTY / AMT</span>
          </div>
          <div style={{ borderTop: '1px dashed #000', margin: '4px 0' }} />
          {rows.map((r, i) => (
            <div key={i} style={{ marginBottom: 4 }}>
              <div style={{ whiteSpace: 'normal', wordBreak: 'break-word' }}>{r.left}</div>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 10 }}>
                <span>
                  x{r.qty} @ ${Number(r.price).toFixed(2)}
                </span>
                <span>${Number(r.amount).toFixed(2)}</span>
              </div>
            </div>
          ))}
          <div style={{ borderTop: '1px dashed #000', margin: '6px 0' }} />
          <div style={{ display: 'flex', justifyContent: 'space-between' }}>
            <span>{L.totalUnits}</span>
            <strong>{ticketUnits}</strong>
          </div>
          <div style={{ display: 'flex', justifyContent: 'space-between', fontWeight: 700 }}>
            <span>{L.total}</span>
            <span>${ticketTotal.toFixed(2)}</span>
          </div>
        </div>
      </>
    );
  }

  return (
    <>
      <style>{`
        @media print {
          #invoice-print.ticket-print {
            width: 80mm !important;
            max-width: 80mm !important;
            margin: 0 auto !important;
            box-shadow: none !important;
          }
          #invoice-print.ticket-print .invoice-inner {
            padding: 8px !important;
          }
          #invoice-print.ticket-print .invoice-store-grid {
            grid-template-columns: 1fr !important;
            gap: 8px !important;
          }
          #invoice-print.ticket-print .invoice-header-title {
            font-size: 16px !important;
            line-height: 1.2 !important;
          }
          #invoice-print.ticket-print table th,
          #invoice-print.ticket-print table td {
            padding: 6px 4px !important;
            font-size: 11px !important;
          }
          #invoice-print.ticket-print .invoice-total-box {
            width: 100% !important;
          }
        }
      `}</style>
      <div className="bg-white text-slate-800 max-w-3xl mx-auto shadow-sm print:shadow-none" id="invoice-print">
        <div className="p-8 md:p-12 invoice-inner">
          <div className="border-b-2 border-slate-800 pb-5 mb-6">
            <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4">
              <div>
                <p className="text-[10px] font-semibold text-slate-500 uppercase tracking-[0.2em] mb-1">Eternal Cosmetics</p>
                <h1 className="text-2xl font-bold text-slate-900 tracking-tight invoice-header-title">ETERNAL COSMETICS, LLC</h1>
                <p className="text-sm text-slate-600 mt-2">7NW 84TH ST, MIAMI, FL 33166</p>
                <p className="text-sm text-slate-600">TEL: (305) 12345678</p>
              </div>
              <div className="text-right sm:text-right">
                <div className="inline-block px-3 py-1 bg-slate-900 text-white text-xs font-semibold uppercase tracking-wider rounded-sm">{L.invoice}</div>
                <p className="text-sm font-medium text-slate-900 mt-3">{invoiceNumber || '—'}</p>
                <p className="text-sm text-slate-600">
                  {L.date}: {date}
                </p>
              </div>
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-8 mb-8 invoice-store-grid">
            <div>
              <p className="text-[11px] font-semibold text-slate-500 uppercase tracking-wider mb-2">{L.clientStore}</p>
              <p className="text-sm font-semibold text-slate-900">{storeName || '—'}</p>
            </div>
            <div>
              <p className="text-[11px] font-semibold text-slate-500 uppercase tracking-wider mb-2">{L.vendor}</p>
              <p className="text-sm font-semibold text-slate-900">{vendorDisplay}</p>
            </div>
          </div>

          <div className="overflow-hidden border border-slate-200">
            <table className="w-full text-sm">
              <thead>
                {viewMode === 'product' ? (
                  <tr className="bg-slate-800 text-white">
                    <th className="text-left py-3 px-4 font-semibold w-14 text-center">{L.qty}</th>
                    <th className="text-left py-3 px-4 font-semibold w-24">{L.sku}</th>
                    <th className="text-left py-3 px-4 font-semibold">{L.description}</th>
                    <th className="text-right py-3 px-4 font-semibold w-24">{L.unitPrice}</th>
                    <th className="text-right py-3 px-4 font-semibold w-28">{L.amount}</th>
                  </tr>
                ) : (
                  <tr className="bg-slate-800 text-white">
                    <th className="text-left py-3 px-4 font-semibold w-14 text-center">{L.qty}</th>
                    <th className="text-left py-3 px-4 font-semibold w-24">{L.code}</th>
                    <th className="text-left py-3 px-4 font-semibold">{L.presentation}</th>
                    <th className="text-right py-3 px-4 font-semibold w-24">{L.unitPrice}</th>
                    <th className="text-right py-3 px-4 font-semibold w-28">{L.amount}</th>
                  </tr>
                )}
              </thead>
              <tbody>
                {viewMode === 'product'
                  ? productRows.map((item, index) => (
                      <tr key={index} className="border-b border-slate-100 last:border-0 hover:bg-slate-50/50">
                        <td className="py-3 px-4 text-center text-slate-700">{item.qty}</td>
                        <td className="py-3 px-4 text-slate-700">{displaySkuCell(item)}</td>
                        <td className="py-3 px-4 text-slate-900">{item.description || '—'}</td>
                        <td className="py-3 px-4 text-right text-slate-700">${Number(item.price).toFixed(2)}</td>
                        <td className="py-3 px-4 text-right font-medium text-slate-900">${Number(item.amount).toFixed(2)}</td>
                      </tr>
                    ))
                  : familyRows.map((row, index) => (
                      <tr key={`f-${index}`} className="border-b border-slate-100 last:border-0 hover:bg-slate-50/50">
                        <td className="py-3 px-4 text-center text-slate-700">{row.qty}</td>
                        <td className="py-3 px-4 text-slate-700">{row.code || '—'}</td>
                        <td className="py-3 px-4 text-slate-900">{row.presentationDesc || '—'}</td>
                        <td className="py-3 px-4 text-right text-slate-700">${Number(row.price).toFixed(2)}</td>
                        <td className="py-3 px-4 text-right font-medium text-slate-900">${Number(row.amount).toFixed(2)}</td>
                      </tr>
                    ))}
                {(viewMode === 'product' ? items.length === 0 : familyRows.length === 0) && (
                  <tr>
                    <td colSpan={5} className="py-8 px-4 text-center text-slate-400 text-sm">
                      {L.noItems}
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>

          <div className="flex justify-end mt-8">
            <div className="w-64 border-t-2 border-slate-200 pt-4 invoice-total-box">
              <div className="flex justify-between text-sm mb-1">
                <span className="text-slate-600">{L.totalUnits}</span>
                <span className="font-medium text-slate-800">{totalPcs}</span>
              </div>
              <div className="flex justify-between text-lg font-bold text-slate-900 mt-3 pt-2 border-t border-slate-100">
                <span>{L.total}</span>
                <span>${totalAmount.toFixed(2)}</span>
              </div>
            </div>
          </div>

          {comments && (
            <div className="mt-8 pt-6 border-t border-slate-200">
              <p className="text-[11px] font-semibold text-slate-500 uppercase tracking-wider mb-2">{L.observations}</p>
              <p className="text-sm text-slate-700">{comments}</p>
            </div>
          )}

          <div className="mt-10 pt-4 border-t border-slate-100 text-center">
            <p className="text-[10px] text-slate-400 uppercase tracking-wider">{L.footer}</p>
          </div>
        </div>
      </div>
    </>
  );
}
